shared:
  requires: [ ~commit, ~pr ]
  image: buildpack-deps
jobs:
  # Jobs are defined by name.
  # All pipelines have "main" implicitly defined. The definitions in your
  # screwdriver.yaml file will override the implied defaults.
  test:
    steps:
      - export: export GREETING="Hello, world 2!"
      - hello: echo $GREETING
