shared:
  annotations:
    screwdriver.cd/timeout: 2880
  requires: [ ~commit, ~pr ]
  image: buildpack-deps
  environment:
    MYSQL_HOST: 20.222.205.247
    MYSQL_USER: test
    MYSQL_PASSWD: test
    MYSQL_DB: test
    CPU: 8
    MEM: 4368709120
    LOW: 4
    MEDIUM: 6
    HIGH: 8
    STEP_WIDTH: 891289600
    TEST_DURATION: 30
    TEST_WORKLOAD_001: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=4 --table_size=10000 --threads=${LOW} --time=${TEST_DURATION} oltp_read_write run
jobs:
   run_test:
    template: db-auto-tune/db-auto-tune-template@1.0.0
    steps:
     - postsysbench-download: wget -qO - https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | bash
     - postsysbench-deploy: apt-get install -y sysbench
     - postsysbench-verify: sysbench --help
     - postclient-install: apt-get install -y default-mysql-client
     - postconn-test: mysql -u ${MYSQL_USER} -p${MYSQL_PASSWD} -h ${MYSQL_HOST} -e "show variables like 'hostname';" 
     - postdb-create: mysql -u ${MYSQL_USER} -p${MYSQL_PASSWD} -h ${MYSQL_HOST} -e "drop database if exists ${MYSQL_DB}; create database ${MYSQL_DB};"
     - postdata-load: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=4 --table_size=10000 --threads=${LOW} oltp_common prepare
     - postexec-work: ${TEST_WORKLOAD_001}
